### ISSUE TITLE
debs run redishappy as root by default

### ISSUE THREAD

**Issue by dominics** [mdevilliers/redishappy#31]
If you're only supporting upstart >= 1.4, you can use setuid/setgid. Otherwise, you could be using start-stop-daemon to switch to a less privileged user.

(I'm replacing the upstart script post-deb-install via Puppet, so not blocking me.)

**Comment by dominics** [comment]
I'm using redishappy-consul, so no issues with low-numbered ports there (it uses 8300-8600 roughly), and it doesn't need root to flip the Consul data.

Happy to help, but it might take a little while until I get around to it. At this stage, it looks like the hard bit will be convincing FPM to generate packages that create a system user (e.g. https://github.com/jordansissel/fpm/issues/831). Editing the upstart script is easy enough, but I don't think we should run as any of the built-in system users.

**Comment by dominics** [comment]
Wow, OK, so the [pre-install](https://github.com/mdevilliers/redishappy/blob/master/build/local-scripts/preinstall-redishappy-consul) already ensures the user is there? Should just be adding the `setuid`/`setgid` for the redishappy-consul upstart service, and then making sure the log/lib dir is writable by that user.

**Comment by dominics** [comment]
Code attached :+1:

**Comment by mdevilliers** [comment]
Coolio - I've merged this in and tweaked the username. I've tested it using the vagrant build and it looks like it works.

If you could give it the once over and confirm I'll close of the ticket.

Thanks again for your help,

Mark

**Comment by dominics** [comment]
Looks good to me. If we're going with a redishappy group as well, we should tweak the setgid to be redishappy (currently still haproxy): https://github.com/mdevilliers/redishappy/blob/master/build/deb_upstart/redishappy-consul-service#L11

Otherwise, cool to close.

**Comment by mdevilliers** [comment]
All done.

It would be cool if in the future you could give us some feedback on any production issues you find - we are still at the stage of "it works for us" but it would be great to find out if it is generally useful. 

Feel free to email me - markdevilliers at gmail dot com.

Thanks again,

Mark
