### ISSUE TITLE
unable to find deb package

### ISSUE THREAD

**Issue by grounded042** [mdevilliers/redishappy#45]
Where can I find the deb packages for this? Are they available without me having to build them myself?

**Comment by mdevilliers** [comment]
Hey,

You will have to build them yourself 

If you have vagrant installed it is pretty straight forward -
```
vagrant up
```

The packages are automatically built to - $GOPATH/src/github.com/redishappy/

Thanks

**Comment by grounded042** [comment]
Wasn't sure if they were offered pre-built or not. Thanks!
