### ISSUE TITLE
IPv6 with Redis

### ISSUE THREAD

**Issue by quulah** [mdevilliers/redishappy#50]
I have Redis and Sentinels running on IPv6.

When configuring redishappy-consul, I set "[::1]" for the Sentinel and Consul addresses, which seems to work.

After that though, I start getting this error:

```
ERROR: 2016/06/15 08:06:05 manager.go:83: Error starting monitor fdf1:a315:9433:8014:f816:3eff:fe1a:288c:26379 : dial tcp: too many colons in address fdf1:a315:9433:8014:f816:3eff:fe1a:288c:26379
ERROR: 2016/06/15 08:06:05 pubsubclient.go:18: PubSubClient Error connecting to fdf1:a315:9433:8014:f816:3eff:fef9:96c3:26379 : dial tcp: too many colons in address fdf1:a315:9433:8014:f816:3eff:fef9:96c3:26379
```

**Comment by quulah** [comment]
I'm not a Go guy, but might be [GetLocation()](https://github.com/mdevilliers/redishappy/blob/5ee4266df3b35d6531262da2ef64c253e705ada1/types/sentinel.go#L12) that is causing the problem.

It returns %s:%s host and port. Which is then used at least [here](https://github.com/mdevilliers/redishappy/blob/5ee4266df3b35d6531262da2ef64c253e705ada1/sentinel/monitor.go#L25) to set the uri.

**Comment by mdevilliers** [comment]
Okay - it looks like when using IPV6 the socket libraries in Golang expect your url/port to kinda look like this -

```
[fdf1:a315:9433:8014:f816:3eff:fe1a:288c:26379]
```

Notice the enclosing "[" and "]"

You could try adjusting your config but expect to run into other problems later on - we do have one bit of code that expects IPV4. If you could try and reposrt back that would be awesome?

**Comment by quulah** [comment]
Thanks, seems to be working.

I made a quick hack earlier that added the missing []'s to the IPv6 address, but that looks a lot cleaner.

**Comment by mdevilliers** [comment]
Thanks for getting back to me - I'll merge.
