### ISSUE TITLE
HAProxy tcp-check or redis-check

### ISSUE THREAD

**Issue by samof76** [mdevilliers/redishappy#57]
How is redishappy with HAProxy better than what HAProxy does with [tcp-check](http://blog.haproxy.com/2014/01/02/haproxy-advanced-redis-health-check/) or [redis-check](http://cbonte.github.io/haproxy-dconv/1.7/configuration.html#option redis-check)?

**Comment by mdevilliers** [comment]
Hey,

redis-check - just checks that the 'thing-you-think-is-redis' speaks the redis protocol
tcp-check - (using the example you linked to) can check that the redis instance is the master before writing to it.
redishappy - will rewrite the haproxy config to point at the redis instance the **is** the master. 

At the time of writing when redis instances come on-line they announce themselves as the master.

So in the case of tcp-check HAProxy will start sending writes to them. These writes will be discarded when the redis instance is made a slave of the master.

Hope all that makes sense,

Mark

**Comment by samof76** [comment]
Hey thanks for that! Closing this issue, as it was just a query.
